---
title: "Match ML Splitsample Results"
author: "Noah Sebek"
date: "September 25, 2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

Sys.setenv(
  PATH = paste(
    "/export/opt/texlive/2018/bin/x86_64-linux",
    Sys.getenv("PATH"),
    sep = ":"
  )
)

library(kableExtra)
library(knitr)

combined_models <- readRDS(file = "combined_models.Rds")

models_cf <- combined_models[[1]]
models_xrf <- combined_models[[2]]

print_all_model_tables <- function(model_list){
  cat("\n")
  for (outcome in names(model_list)){
    cat("### ", outcome, " \n")
    table_names <- names(model_list[[outcome]])
    
    for (table in table_names){
      
      if (table %in% "calibration_tests_naive_linear" ){table_name <- "naive calibration test quartile dummies"}
      else if (table %in% "calibration_tests_naive_quartile_dummies"){table_name <- "naive calibration test linear"}
      else {table_name <- table}
      
      current_table <- model_list[[outcome]][[table]]
      colnames(current_table) <- gsub("_", " ", colnames(current_table))
      
      
      current_table %>% kable(booktabs=T,
                              escape=T, digits=3,
                              caption = paste0(gsub("_", " ", table_name), " for ", outcome),
                              align = rep('c', ncol(.))) %>%
        column_spec(2:ncol(current_table), width = '1.2cm') %>% 
        kable_styling(latex_options = c(#'striped', 'scale_down',
        'HOLD_position'
        )) %>% print()
      
      
    }
    cat('\\newpage')
  }
}

```

# Causal Forest


```{r, results='asis', include=T, echo=F, fig.height=4.4, fig.width=7.5,  warning=F}

models_cf %>% print_all_model_tables()

```


# X-Learner - GRF Implementation

```{r, results='asis', include=T, echo=F, fig.height=4.4, fig.width=7.5,  warning=F}

models_xrf %>% print_all_model_tables()

```